import { useState } from 'react';
import { useAgent } from '../context/AgentContext.jsx';
import ReactMarkdown from 'react-markdown';

function FinalArticleView() {
  const { state, reset } = useAgent();
  const { finalArticle, wordCount, topic, outline } = state;
  const [copied, setCopied] = useState(false);

  if (!finalArticle) {
    return null;
  }

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(finalArticle);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy:', err);
    }
  };

  const handleDownload = () => {
    const blob = new Blob([finalArticle], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${outline?.title || 'article'}.md`.replace(/[^a-z0-9]/gi, '-').toLowerCase();
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleNewArticle = () => {
    reset();
  };

  return (
    <div className="space-y-6">
      {/* Success banner */}
      <div className="bg-green-50 border border-green-200 rounded-lg p-4 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <span className="text-2xl">🎉</span>
          <div>
            <h3 className="font-semibold text-green-800">Article Complete!</h3>
            <p className="text-sm text-green-600">
              Your {wordCount} word article is ready
            </p>
          </div>
        </div>
        <button
          onClick={handleNewArticle}
          className="px-4 py-2 bg-green-600 text-white text-sm font-medium rounded-lg hover:bg-green-700 transition-colors"
        >
          Write Another
        </button>
      </div>

      {/* Article card */}
      <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
        {/* Header */}
        <div className="px-6 py-4 border-b border-gray-100 flex items-center justify-between">
          <div>
            <h2 className="text-xl font-bold text-gray-900">{outline?.title || 'Article'}</h2>
            <p className="text-sm text-gray-500 mt-1">
              Topic: {topic}
            </p>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={handleCopy}
              className={`
                px-4 py-2 text-sm font-medium rounded-lg transition-colors
                ${copied
                  ? 'bg-green-100 text-green-700'
                  : 'bg-gray-100 text-gray-700 hover:bg-gray-200'}
              `}
            >
              {copied ? '✓ Copied!' : 'Copy'}
            </button>
            <button
              onClick={handleDownload}
              className="px-4 py-2 bg-blue-600 text-white text-sm font-medium rounded-lg hover:bg-blue-700 transition-colors"
            >
              Download .md
            </button>
          </div>
        </div>

        {/* Article content */}
        <div className="px-6 py-8">
          <article className="prose prose-lg max-w-none">
            <ReactMarkdown>{finalArticle}</ReactMarkdown>
          </article>
        </div>

        {/* Footer stats */}
        <div className="px-6 py-4 bg-gray-50 border-t border-gray-100">
          <div className="flex items-center justify-between text-sm text-gray-500">
            <span>{wordCount} words</span>
            <span>Generated by Blog Writing Agent</span>
          </div>
        </div>
      </div>
    </div>
  );
}

export default FinalArticleView;
